name: Build and Deploy
on:
  push:
  repository_dispatch:
    types: [build-and-deploy]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pages

    steps:
      - name: Checkout landing page
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install
        run: npm install
      - name: Build
        run: npm run build

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: braden-wilson/docs  # Changed
          path: docs

      - name: Install docs
        run: |
          ls
          yarn install
      
      - name: Build site with antora
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: antora-playbook.yml

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          BRANCH: master
          FOLDER: out
          REPOSITORY_NAME: braden-wilson/braden-wilson.github.io  # Changed
          CLEAN: true
